#!/usr/bin/env bash

set -eu -o pipefail

CB_PORT=8080
HOSTADDR=localhost

## host OS addr of WSL (networkingMode=NAT)
#HOSTADDR=$(ip route show | grep -i default | awk '{ print $3 }')

curl -sf -X POST -d "$1" "${HOSTADDR}:${CB_PORT}/browse"
